name: Build and Deploy

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch: # allow manual runs too

permissions:
  contents: write   # needed for pushing to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build + Generate
        run: CI=false npm run predeploy

      - name: Commit and push specific LFS file changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/dataArchive.json.br
          if git diff-index --quiet HEAD; then
            echo "No changes in data/dataArchive.json.br to commit. Exiting."
          else
            git commit -m "Auto-generated update to dataArchive.json.br from cron job"
            git push
            echo "Changes in data/dataArchive.json.br committed and pushed."
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: setsonstream.tv

